import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { Grid, Pagination, Box } from "@mui/material";
import { IComicResponse } from "types";
import { useEffect, useState, ChangeEvent } from "react";
import { useRouter } from "next/router";
import {
  getComicsByPage,
  getComics,
} from "dh-marvel/services/marvel/marvel.service";
import CardComponent from "dh-marvel/components/card/card";

interface Props {
  cards: IComicResponse;
}

const Index: NextPage<Props> = ({ cards }) => {
  const router = useRouter();
  const [page, setPage] = useState<number>(1);
  const [data, setData] = useState<IComicResponse>();

  useEffect(() => {
    localStorage.clear();
  }, []);

  useEffect(() => {
    if (page !== null) {
      router.push(`/?page=${page}`, undefined, { shallow: true });
      getComicsByPage(12, page).then((data: IComicResponse) => {
        data.code === 200 ? setData(data) : null;
      });
    }
  }, [page]);

  const handleChange = (event: ChangeEvent<unknown>, value: number) => {
    setPage(value);
  };

  const pages: number =
    cards?.data?.total !== undefined ? Math.ceil(cards.data.total / 12) : 1;

  return (
    <>
      <Head>
        <title>DH MARVEL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ margin: "20px" }}>
        <BodySingle title={"Comics"}></BodySingle>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            marginBottom: "20px",
          }}
        >
          <Pagination count={pages} page={page} onChange={handleChange} />
        </Box>
        <Grid container columns={4} spacing={2}>
          {data !== undefined
            ? data.data.results.map((comic, key) => (
                <Grid key={key} item xs={1}>
                  <CardComponent comic={comic} />
                </Grid>
              ))
            : cards?.data.results.map((comic, key) => (
                <Grid key={key} item xs={1}>
                  <CardComponent comic={comic} />
                </Grid>
              ))}
        </Grid>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            marginTop: "20px",
          }}
        >
          <Pagination count={pages} page={page} onChange={handleChange} />
        </Box>
      </Box>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const cards = await getComics(0, 12);
  return { props: { cards } };
};

export default Index;
